export const dynamic = "force-dynamic";

import Link from "next/link";
import { Shield, Lock, Server, Eye, CreditCard, FileText } from "lucide-react";

export const metadata = { title: "Security & Data — Guilded" };

const SECTIONS = [
  {
    icon:  Lock,
    title: "End-to-End Encryption",
    body:  "All data transmitted between your browser and Guilded is encrypted using TLS 1.3. Passwords are never stored in plaintext — they are hashed using Argon2, a memory-hard algorithm designed to resist brute-force attacks.",
  },
  {
    icon:  FileText,
    title: "Credit Report Handling",
    body:  "When you upload a credit report PDF, our system extracts the text content and then permanently deletes the raw file. We do not store PDFs. Only the structured account data extracted from the report is retained — and only for as long as your account is active.",
  },
  {
    icon:  Eye,
    title: "What We Can See",
    body:  "Guilded staff can access account metadata (email, tier, usage counts) for support purposes. We cannot read your credit report content unless you explicitly share it in a support ticket. Your financial data is yours.",
  },
  {
    icon:  Server,
    title: "Infrastructure",
    body:  "Guilded runs on secured infrastructure with access controls, automated backups, and monitoring. Our database uses row-level encryption for sensitive fields. Authentication tokens expire after 30 days.",
  },
  {
    icon:  CreditCard,
    title: "Payment Security",
    body:  "Billing is handled by Stripe, a PCI DSS Level 1 certified payment processor. Guilded never sees, stores, or logs your payment card details. We receive only transaction confirmation and subscription status.",
  },
  {
    icon:  Shield,
    title: "AI Processing",
    body:  "AI responses are generated by OpenAI&apos;s API. Your prompts and our responses are transmitted to OpenAI for processing. We do not store conversation history server-side beyond the current session. Review OpenAI&apos;s privacy policy at openai.com/privacy.",
  },
];

export default function SecurityPage() {
  return (
    <div className="min-h-screen bg-slate-950 px-4 py-12">
      <div className="mx-auto max-w-2xl">
        <div className="flex items-center gap-2.5 mb-8">
          <Shield size={18} className="text-gold" />
          <Link href="/" className="text-sm font-bold text-white">Guilded</Link>
        </div>

        <div className="flex items-center gap-2 mb-4">
          <Lock size={16} className="text-gold" />
          <h1 className="text-2xl font-semibold text-slate-100">Security &amp; Data</h1>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          Guilded handles sensitive financial data. Here&apos;s exactly how we protect it.
        </p>

        <div className="mt-8 space-y-6">
          {SECTIONS.map(({ icon: Icon, title, body }) => (
            <div key={title} className="rounded-xl border border-slate-800 bg-slate-900/60 px-5 py-4">
              <div className="flex items-center gap-2.5 mb-2">
                <Icon size={15} className="text-gold shrink-0" />
                <h2 className="text-sm font-semibold text-slate-100">{title}</h2>
              </div>
              <p className="text-sm text-slate-400 leading-relaxed">{body}</p>
            </div>
          ))}
        </div>

        <div className="mt-10 rounded-xl border border-slate-800 bg-slate-900/30 px-5 py-4">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
            Report a Security Issue
          </p>
          <p className="text-sm text-slate-400">
            If you discover a security vulnerability, please contact us at{" "}
            <a href="mailto:guilded@jesseboudreau.com" className="text-gold hover:underline">
              guilded@jesseboudreau.com
            </a>{" "}
            before public disclosure. We take all reports seriously.
          </p>
        </div>

        <div className="mt-10 border-t border-slate-800 pt-6 text-xs text-slate-600">
          <Link href="/privacy"       className="hover:text-slate-400 mr-4">Privacy Policy</Link>
          <Link href="/terms"         className="hover:text-slate-400 mr-4">Terms of Service</Link>
          <Link href="/ai-disclaimer" className="hover:text-slate-400">AI Disclaimer</Link>
        </div>
      </div>
    </div>
  );
}
